es:
  languageName: Espa침ol
  contentDir: content/es
  copyright: "Copyright &copy; {{< current_year >}} [ferchaure](https://github.com/ferchaure) . All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  weight: 1
  title: "Foro de la Memoria de Mataderos"
  params:
    description: "Descripci칩n del Sitio"
    ### accessibility ###
    #accessibility:
    #  skip_text: "Skip to content"
    #  help_text: "Accessibility Statement"
    #  help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Inscripci칩n a Cocama2025"
      link: "https://sites.google.com/view/cocama2025/inicio"
    footer_cta:
      text: "Inscripci칩n a Cocama2025"
      link: "https://sites.google.com/view/cocama2025/inicio"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "Nosotros"
      url: "/about"
      weight: 1
    - identifier: "cocama"
      name: "CoCaMa"
      url: "/cocama/"
      weight: 2
      #parent: "cocama"
    - identifier: "blog"
      name: "Blog"
      url: "https://forommataderos.blogspot.com/"
      weight: 2
    - identifier: "contacto"
      name: "Contacto"
      url: "/about/contact/"
      weight: 4    