######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/LogoForo.gif"
logo_on_black: "/img/LogoForo.gif"
custom_js: []
custom_css: ["/css/overrides.css"]

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/LogoForo.gif"]

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/foromataderos/wall/"
  flickr: ""
  github: ""
  instagram: "https://www.instagram.com/forodelamemoriamataderos/"
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: "https://x.com/forommataderos"
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
